### ISSUE TITLE
u2fval.conf is missing in conf/

### ISSUE THREAD

**Issue by jpmens** [Yubico/u2fval#11] opened 2015-10-13 15:17 UTC
The sample configuration file which is supposed to reside in `conf/u2fval.conf` has "gone away"? ;-)

`python setup.py install` requires it.

**Comment by jpmens** [comment] 2015-10-13 15:17
For the record, I found this in an older .tar file:

```
# Database configuration string
DATABASE_CONFIGURATION = 'sqlite:///:memory:'

# If True, use memcached for storing registration and authentication requests
# in progress, instead of persisting them to the database.
USE_MEMCACHED = False

# If memcached is enabled, use these servers.
MEMCACHED_SERVERS = ['127.0.0.1:11211']

# Add files containing trusted metadata JSON to the directory below.
METADATA = '/etc/yubico/u2fval/metadata/'

# Allow the use of untrusted (for which attestation cannot be verified using
# the available trusted metadata) U2F devices.
ALLOW_UNTRUSTED = False
```

**Comment by dainnilsson** [comment] 2015-10-13 15:19
Which version is it missing from? I see it in 0.9.1...

**Comment by jpmens** [comment] 2015-10-13 15:21
Master branch which I just pulled.

**Comment by dainnilsson** [comment] 2015-10-13 15:22
Duplicate of #1

**Closed by dainnilsson** 2015-10-13 15:22 UTC
Labels: duplicate

**Comment by jpmens** [comment] 2015-10-13 15:28
It seems I'm not alone ...

Might I suggest a slight rewording of the README? The information

```
To build a source release tar ball, run this command:
    python setup.py sdist
The resulting build will be created in the dist/ subdirectory.

...
Configuration is kept in /etc/yubico/u2fval/u2fval.conf
```

doesn't tell me that I **must** build a source release from the git repo.

**Comment by dainnilsson** [comment] 2015-10-14 07:51
Sure, please suggest a change (as a comment or PR) that you think would make it clearer. My reasoning has been that users will read the section titled "Installation", which outline how to install from pip, as well as from a source release tar ball.

**Comment by dainnilsson** [comment] 2015-10-14 07:56
Also see #12 as a potentially better solution to the problem.

**Comment by jpmens** [comment] 2015-10-14 08:02
I this something along these lines make it clearer, at least to me, and #12 should be done as well.


## Installation

u2flib-server is installable by one of two means:

1. via `pip`
2. via `git`

### Installation via pip

Run

```
$ pip install u2fval
```

Alternatively, you can run:

```
$ pip install u2fval-<version>.tar.gz
```

where the `.tar.gz` file is a source release of the project.

### Installation via git

1. Check out the code

```
git clone https://github.com/Yubico/u2fval.git
cd u2fval
git submodule init
git submodule update
```

2. Build a source release tar ball by running

```
python setup.py sdist
```

The resulting build is created in the `dist/` subdirectory. Install this using pip
as described above.

**Comment by jpmens** [comment] 2015-10-14 08:11
I will reword this a bit in a PR

**Comment by dainnilsson** [comment] 2015-10-14 08:13
Thanks! I like what you've got so far.
